
import {generate, uuid, UUID, UUIDAutogenerated} from '..';


let id = generate();
// console.log(`id: ${id.toString()}, json: ${JSON.stringify(id)}`);


@uuid()
class User {

    @UUIDAutogenerated()
    public readonly id: UUID;
    public readonly name: string;
    public readonly email: string;

    public constructor(name: string, email: string) {
        this.name = name;
        this.email = email;
    }

    public toString(): string {
        return `User {id: ${this.id}, name: ${this.name}, email: ${this.email}`;
    }

}

console.log(User);

// [
//     new User('user1', 'user1@domain.com'),
//     new User('user2', 'user2@domain.com'),
//     new User('user3', 'user3@domain.com')
//
// ].forEach(u => console.log(u.toString(), JSON.stringify(u)));
